---
- include_tasks: rules.yml

- include_tasks: persist-debian.yml
  when:
    - ansible_os_family == 'Debian'
    - firewall_persist_rules == true

- include_tasks: persist-redhat.yml
  when:
    - ansible_os_family == 'RedHat'
    - firewall_persist_rules == true
